### ISSUE TITLE
WARNING: The following warnings have been detected: WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.DataSourceProvider] with an exception

### ISSUE THREAD

**Issue by heejongkim** [Rappsilber-Laboratory/xiAnnotator#19]
after following the README, the service was still inactive. So, I tried to execute the jar file manually to see it's ok and got the following error msg. I only attached first portion of it.
It seems like very similar to the issue with https://github.com/spotify/dockerfile-maven/issues/90

Do you have any specific Java version for this?

Thanks!

WARNING: The following warnings have been detected: WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/activation/DataSource
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
	at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1311)
	at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1307)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1307)
	at org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1250)
	at org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:83)
	at org.glassfish.jersey.internal.inject.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:144)
	at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:179)
	at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:128)
	at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:179)
	at org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:723)
	at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:678)
	at org.jvnet.hk2.internal.ServiceLocatorImpl

**Comment by heejongkim** [comment]
java 8 resolved the issue.

**Comment by lutzfischer** [comment]
sorry that I did not notice your message before - what java version did you use before?
